-- One-time manual translation batch for customers.name_en and
-- menu_items.name_en, requested because the English language toggle had
-- nothing to fall back to for almost every row. No AI/translation API is
-- wired into this project, so this is a hand-translated pass over the
-- actual current data (pasted by the user), following the same
-- hardcoded UPDATE-per-row pattern as 007_categorize_known_items.sql /
-- 030_categorize_additional_items.sql.
--
-- Test/admin/placeholder customer rows (date-range codes, anything
-- containing "דוגמאות", template/helper rows) are intentionally left
-- untouched (name_en stays NULL) -- confirmed with the user, since an
-- English "translation" of a placeholder like "000000" is meaningless.
--
-- Values use dollar-quoting ($$...$$) instead of single-quoted strings
-- throughout, since several Hebrew names contain a literal apostrophe
-- (e.g. ביץ' קלאב) or double-quote (e.g. תפו"א) and some English
-- translations contain an apostrophe too (e.g. Za'atar) -- dollar-quoting
-- sidesteps escaping either safely.

-- ── Customers ────────────────────────────────────────────────────────
UPDATE customers SET name_en = $$Urban Noga$$ WHERE name = $$אורבן נגה$$;
UPDATE customers SET name_en = $$Oro$$ WHERE name = $$אורו$$;
UPDATE customers SET name_en = $$Itri$$ WHERE name = $$איטרי$$;
UPDATE customers SET name_en = $$Anya$$ WHERE name = $$אניה$$;
UPDATE customers SET name_en = $$Anastasia$$ WHERE name = $$אנסטסיה$$;
UPDATE customers SET name_en = $$Ace$$ WHERE name = $$אס$$;
UPDATE customers SET name_en = $$Ace 89$$ WHERE name = $$אס 89$$;
UPDATE customers SET name_en = $$Boutique Dizengoff$$ WHERE name = $$בוטי דיזינגוף$$;
UPDATE customers SET name_en = $$Boutique Sarona$$ WHERE name = $$בוטי שרונה$$;
UPDATE customers SET name_en = $$Beach Club$$ WHERE name = $$ביץ' קלאב$$;
UPDATE customers SET name_en = $$Beit Alaya$$ WHERE name = $$בית אלאיה$$;
UPDATE customers SET name_en = $$Beit Alaya (Ligurian)$$ WHERE name = $$בית אלאיה (ליגורי)$$;
UPDATE customers SET name_en = $$Bnei HaKikar$$ WHERE name = $$בני הכיכר$$;
UPDATE customers SET name_en = $$Brasserie 18$$ WHERE name = $$בראסרי 18$$;
UPDATE customers SET name_en = $$Brasserie 18 (New Menu)$$ WHERE name = $$בראסרי 18 תפריט חדש$$;
UPDATE customers SET name_en = $$Gazetti$$ WHERE name = $$גאזטי$$;
UPDATE customers SET name_en = $$Dor$$ WHERE name = $$דור$$;
UPDATE customers SET name_en = $$Delisha$$ WHERE name = $$דלישא$$;
UPDATE customers SET name_en = $$Drisco$$ WHERE name = $$דריסקו$$;
UPDATE customers SET name_en = $$Drisco (New Menu)$$ WHERE name = $$דריסקו תפריט חדש$$;
UPDATE customers SET name_en = $$Hok HaTavor$$ WHERE name = $$הוק התבור$$;
UPDATE customers SET name_en = $$Hok Trumpeldor$$ WHERE name = $$הוק טרומפלדור$$;
UPDATE customers SET name_en = $$Hamburger$$ WHERE name = $$המבורגר$$;
UPDATE customers SET name_en = $$Hershele$$ WHERE name = $$הרשלה$$;
UPDATE customers SET name_en = $$Yaya Levinsky$$ WHERE name = $$יאיא לוינסקי$$;
UPDATE customers SET name_en = $$Yedidya$$ WHERE name = $$ידידיה$$;
UPDATE customers SET name_en = $$Yulia$$ WHERE name = $$יוליה$$;
UPDATE customers SET name_en = $$YomYom$$ WHERE name = $$יוםיום$$;
UPDATE customers SET name_en = $$Yayin BaKerem$$ WHERE name = $$יין בכרם$$;
UPDATE customers SET name_en = $$Labeet$$ WHERE name = $$לאבאיט$$;
UPDATE customers SET name_en = $$La Terrasse$$ WHERE name = $$לה טראסה$$;
UPDATE customers SET name_en = $$Liber$$ WHERE name = $$ליבר$$;
UPDATE customers SET name_en = $$Ma Julie$$ WHERE name = $$מה ג׳ולי$$;
UPDATE customers SET name_en = $$Mitzi$$ WHERE name = $$מיצי$$;
UPDATE customers SET name_en = $$Menu Vino$$ WHERE name = $$מנו וינו$$;
UPDATE customers SET name_en = $$Menu Vino Adina$$ WHERE name = $$מנו וינו עדינה$$;
UPDATE customers SET name_en = $$Nordinio$$ WHERE name = $$נורדיניו$$;
UPDATE customers SET name_en = $$Sursato$$ WHERE name = $$סורסטו$$;
UPDATE customers SET name_en = $$Pina$$ WHERE name = $$פינה$$;
UPDATE customers SET name_en = $$Panda$$ WHERE name = $$פנדה$$;
UPDATE customers SET name_en = $$Panda (New Menu)$$ WHERE name = $$פנדה תפריט חדש$$;
UPDATE customers SET name_en = $$Facility$$ WHERE name = $$פסיליטי$$;
UPDATE customers SET name_en = $$Fraiso$$ WHERE name = $$פראיסו$$;
UPDATE customers SET name_en = $$Frizo$$ WHERE name = $$פריזו$$;
UPDATE customers SET name_en = $$Frenkel Cafe$$ WHERE name = $$פרנקל קפה$$;
UPDATE customers SET name_en = $$Tzkauli$$ WHERE name = $$צקאולי$$;
UPDATE customers SET name_en = $$Tzkauoli$$ WHERE name = $$צקואולי$$;
UPDATE customers SET name_en = $$Kaldi$$ WHERE name = $$קאלדי$$;
UPDATE customers SET name_en = $$Common People$$ WHERE name = $$קאמן פיפל$$;
UPDATE customers SET name_en = $$Kohi$$ WHERE name = $$קוהי$$;
UPDATE customers SET name_en = $$Common People$$ WHERE name = $$קומון פיפל$$;
UPDATE customers SET name_en = $$Coffee Brands$$ WHERE name = $$קופי ברנדס$$;
UPDATE customers SET name_en = $$Corner Cafe$$ WHERE name = $$קורנר קפה$$;
UPDATE customers SET name_en = $$Corner - Petit Vert Cafe$$ WHERE name = $$קורנר-פטיוור קפה$$;
UPDATE customers SET name_en = $$Kiosko$$ WHERE name = $$קיוסקו$$;
UPDATE customers SET name_en = $$Cafe 14$$ WHERE name = $$קפה 14$$;
UPDATE customers SET name_en = $$Cafe Asif$$ WHERE name = $$קפה אסיף$$;
UPDATE customers SET name_en = $$Cafe BaNachala$$ WHERE name = $$קפה בנחלה$$;
UPDATE customers SET name_en = $$Cafe BaNachala (BaKerem)$$ WHERE name = $$קפה בנחלה (בכרם)$$;
UPDATE customers SET name_en = $$Cafe Dizengoff$$ WHERE name = $$קפה דיזינגוף$$;
UPDATE customers SET name_en = $$Cafe HaKerem, Ganei Tikva$$ WHERE name = $$קפה הכרם גני תקווה$$;
UPDATE customers SET name_en = $$Cafe HaKerem, Ganei Tikva - 10% Discount$$ WHERE name = $$קפה הכרם גני תקווה- 10% הנחה$$;
UPDATE customers SET name_en = $$Cafe HaMesila$$ WHERE name = $$קפה המסילה$$;
UPDATE customers SET name_en = $$Cafe HaMesila (New Menu)$$ WHERE name = $$קפה המסילה תפריט חדש$$;
UPDATE customers SET name_en = $$Cafe Zohar$$ WHERE name = $$קפה זוהר$$;
UPDATE customers SET name_en = $$Cafe Anan$$ WHERE name = $$קפה ענן$$;
UPDATE customers SET name_en = $$Cafe Kaldi$$ WHERE name = $$קפה קלדי$$;
UPDATE customers SET name_en = $$Cafe Radical$$ WHERE name = $$קפה רדיקל$$;
UPDATE customers SET name_en = $$Kapsito$$ WHERE name = $$קפסיטו$$;
UPDATE customers SET name_en = $$Rov Cafe$$ WHERE name = $$רוב קפה$$;
UPDATE customers SET name_en = $$Chantal$$ WHERE name = $$שאנטל$$;
UPDATE customers SET name_en = $$Che Vivi$$ WHERE name = $$שה ויוי$$;
UPDATE customers SET name_en = $$Thomas Cafe$$ WHERE name = $$תומס קפה$$;

-- ── Menu items ───────────────────────────────────────────────────────
UPDATE menu_items SET name_en = $$Amsterdam$$ WHERE name_he = $$אמסטרדם$$;
UPDATE menu_items SET name_en = $$Amaretti Pack$$ WHERE name_he = $$אמרטי מארז$$;
UPDATE menu_items SET name_en = $$White Baguette$$ WHERE name_he = $$בגט לבן$$;
UPDATE menu_items SET name_en = $$Baguette + Ciabattas$$ WHERE name_he = $$בגט+ ג׳בטות$$;
UPDATE menu_items SET name_en = $$Almond & Blueberry Bostock$$ WHERE name_he = $$בוסטוק שקדים ואוכמניות$$;
UPDATE menu_items SET name_en = $$Cheese & Leek Burekas$$ WHERE name_he = $$בורקס גבינות וכרישה$$;
UPDATE menu_items SET name_en = $$Triangle Burekas - Cheese & Leek$$ WHERE name_he = $$בורקס משולש - גבינות וכרישה$$;
UPDATE menu_items SET name_en = $$Triangle Burekas - Potato, Onion & Za'atar$$ WHERE name_he = $$בורקס משולש - תפו"א בצל וזעתר$$;
UPDATE menu_items SET name_en = $$Potato, Onion & Za'atar Burekas$$ WHERE name_he = $$בורקס תפו"א בצל וזעתר$$;
UPDATE menu_items SET name_en = $$Potato & Mushroom Burekas$$ WHERE name_he = $$בורקס תפו"א ופטריות$$;
UPDATE menu_items SET name_en = $$Bousha$$ WHERE name_he = $$בושה$$;
UPDATE menu_items SET name_en = $$Walnut Bahusha$$ WHERE name_he = $$בחושה אגוזים$$;
UPDATE menu_items SET name_en = $$Blueberry Bahusha$$ WHERE name_he = $$בחושה אוכמניות$$;
UPDATE menu_items SET name_en = $$Vegan Banana Bahusha$$ WHERE name_he = $$בחושה בננות טבעוני$$;
UPDATE menu_items SET name_en = $$Carrot Bahusha$$ WHERE name_he = $$בחושה גזר$$;
UPDATE menu_items SET name_en = $$Maple Pecan Bahusha$$ WHERE name_he = $$בחושה מייפל פקאן$$;
UPDATE menu_items SET name_en = $$Lemon Poppy Bahusha$$ WHERE name_he = $$בחושה פרג לימון$$;
UPDATE menu_items SET name_en = $$Chocolate Bahusha$$ WHERE name_he = $$בחושה שוקולד$$;
UPDATE menu_items SET name_en = $$Orange Bahusha$$ WHERE name_he = $$בחושה תפוזים$$;
UPDATE menu_items SET name_en = $$Cheese Bagel$$ WHERE name_he = $$בייגל גבינות$$;
UPDATE menu_items SET name_en = $$Beigelach$$ WHERE name_he = $$בייגלה$$;
UPDATE menu_items SET name_en = $$Biscotti$$ WHERE name_he = $$ביסקוטי$$;
UPDATE menu_items SET name_en = $$Biscotti Pack$$ WHERE name_he = $$ביסקוטי מארז$$;
UPDATE menu_items SET name_en = $$Frozen Puff Pastry (1kg)$$ WHERE name_he = $$בצק עלים קפוא (1 ק"ג)$$;
UPDATE menu_items SET name_en = $$Pizza Dough$$ WHERE name_he = $$בצק פיצה$$;
UPDATE menu_items SET name_en = $$Individual Brownie$$ WHERE name_he = $$בראוניז אישי$$;
UPDATE menu_items SET name_en = $$Brownie Bar$$ WHERE name_he = $$בראוניז פס$$;
UPDATE menu_items SET name_en = $$Sunflower Health Bun$$ WHERE name_he = $$בריאות חמניה$$;
UPDATE menu_items SET name_en = $$Vanilla Caramel Brioche$$ WHERE name_he = $$בריוש וניל קרמל$$;
UPDATE menu_items SET name_en = $$Rectangular Brioche$$ WHERE name_he = $$בריוש מלבני$$;
UPDATE menu_items SET name_en = $$Rectangular / Round Brioche$$ WHERE name_he = $$בריוש מלבני / עגול$$;
UPDATE menu_items SET name_en = $$Round Brioche$$ WHERE name_he = $$בריוש עגול$$;
UPDATE menu_items SET name_en = $$Chocolate Brioche$$ WHERE name_he = $$בריוש שוקולד$$;
UPDATE menu_items SET name_en = $$Lime Cheesecake$$ WHERE name_he = $$גבינה ליים$$;
UPDATE menu_items SET name_en = $$Bulk Granola (1kg)$$ WHERE name_he = $$גרנולה בתפזורת (1 ק"ג)$$;
UPDATE menu_items SET name_en = $$Granola Pack$$ WHERE name_he = $$גרנולה מארז$$;
UPDATE menu_items SET name_en = $$Honey Cookies Pack$$ WHERE name_he = $$דובשניות מארז$$;
UPDATE menu_items SET name_en = $$Challah$$ WHERE name_he = $$חלה$$;
UPDATE menu_items SET name_en = $$Challah (Fri/Sat)$$ WHERE name_he = $$חלה (שישי/שבת)$$;
UPDATE menu_items SET name_en = $$Flan Tart (Chalef)$$ WHERE name_he = $$טארט פלאן כשלפ$$;
UPDATE menu_items SET name_en = $$Health Bread (Sunflower)$$ WHERE name_he = $$לחם בריאות (חמניה)$$;
UPDATE menu_items SET name_en = $$Sunflower Health Bread$$ WHERE name_he = $$לחם בריאות חמניה$$;
UPDATE menu_items SET name_en = $$Spelt Bread$$ WHERE name_he = $$לחם כוסמין$$;
UPDATE menu_items SET name_en = $$Country Bread$$ WHERE name_he = $$לחם כפרי$$;
UPDATE menu_items SET name_en = $$Gluten-Free Bread$$ WHERE name_he = $$לחם ללא גלוטן$$;
UPDATE menu_items SET name_en = $$Pecan Sourdough Bread$$ WHERE name_he = $$לחם מחמצת פקאן$$;
UPDATE menu_items SET name_en = $$100% Whole Wheat Bread$$ WHERE name_he = $$לחם מלא 100%$$;
UPDATE menu_items SET name_en = $$Norwegian Bread$$ WHERE name_he = $$לחם נורווגי$$;
UPDATE menu_items SET name_en = $$100% Rye Bread$$ WHERE name_he = $$לחם שיפון 100%$$;
UPDATE menu_items SET name_en = $$Rye Walnut Bread$$ WHERE name_he = $$לחם שיפון אגוזים$$;
UPDATE menu_items SET name_en = $$Challah Bite Rolls$$ WHERE name_he = $$לחמניות ביס חלה$$;
UPDATE menu_items SET name_en = $$Beigelach Roll$$ WHERE name_he = $$לחמניית בייגלה$$;
UPDATE menu_items SET name_en = $$Crumble Brioche Roll$$ WHERE name_he = $$לחמניית בריוש קרמבל$$;
UPDATE menu_items SET name_en = $$Whole Wheat Roll$$ WHERE name_he = $$לחמניית חיטה מלאה$$;
UPDATE menu_items SET name_en = $$Challah Roll (Bite)$$ WHERE name_he = $$לחמניית חלה (ביס)$$;
UPDATE menu_items SET name_en = $$Whole Spelt Roll$$ WHERE name_he = $$לחמניית כוסמין מלא$$;
UPDATE menu_items SET name_en = $$Pretzel Roll$$ WHERE name_he = $$לחמניית פרעצל$$;
UPDATE menu_items SET name_en = $$Pretzel Roll (Bite)$$ WHERE name_he = $$לחמניית פרעצל (ביס)$$;
UPDATE menu_items SET name_en = $$Artichoke Pesto Pastry$$ WHERE name_he = $$מאפה ארטישוק פסטו$$;
UPDATE menu_items SET name_en = $$Savory Cheese Pastry$$ WHERE name_he = $$מאפה גבינות מלוח$$;
UPDATE menu_items SET name_en = $$Coffee & Cocoa Pastry$$ WHERE name_he = $$מאפה קפה וקקאו$$;
UPDATE menu_items SET name_en = $$Cocoa & Chocolate Pastry$$ WHERE name_he = $$מאפה קקאו ושוקולד$$;
UPDATE menu_items SET name_en = $$Corn Pastry$$ WHERE name_he = $$מאפה תירס$$;
UPDATE menu_items SET name_en = $$Orange Pastry$$ WHERE name_he = $$מאפה תפוזים$$;
UPDATE menu_items SET name_en = $$Spinach & Feta Pastry$$ WHERE name_he = $$מאפה תרד ופטה$$;
UPDATE menu_items SET name_en = $$Spinach & Feta Pastry - Frozen$$ WHERE name_he = $$מאפה תרד ופטה - קפוא$$;
UPDATE menu_items SET name_en = $$Walnut Muffin$$ WHERE name_he = $$מאפין אגוזים$$;
UPDATE menu_items SET name_en = $$Blueberry Muffin$$ WHERE name_he = $$מאפין אוכמניות$$;
UPDATE menu_items SET name_en = $$Carrot Muffin$$ WHERE name_he = $$מאפין גזר$$;
UPDATE menu_items SET name_en = $$Chocolate Muffin$$ WHERE name_he = $$מאפין שוקולד$$;
UPDATE menu_items SET name_en = $$Orange Muffin$$ WHERE name_he = $$מאפין תפוזים$$;
UPDATE menu_items SET name_en = $$Olive Parmesan Sourdough$$ WHERE name_he = $$מחמצת זיתים פרמזן$$;
UPDATE menu_items SET name_en = $$White Sourdough$$ WHERE name_he = $$מחמצת לבן$$;
UPDATE menu_items SET name_en = $$100% Rye Sourdough$$ WHERE name_he = $$מחמצת שיפון 100%$$;
UPDATE menu_items SET name_en = $$Mini Cheese & Leek Pastry$$ WHERE name_he = $$מיני גבינות כרישה$$;
UPDATE menu_items SET name_en = $$Mini Danish$$ WHERE name_he = $$מיני דניש$$;
UPDATE menu_items SET name_en = $$Mini Butter Pastry$$ WHERE name_he = $$מיני חמאה$$;
UPDATE menu_items SET name_en = $$Mini Pretzel$$ WHERE name_he = $$מיני פרעצל$$;
UPDATE menu_items SET name_en = $$Mini Butter Croissant - Frozen$$ WHERE name_he = $$מיני קרואסון חמאה- קפוא$$;
UPDATE menu_items SET name_en = $$Mini Chocolate Croissant$$ WHERE name_he = $$מיני קרואסון שוקולד$$;
UPDATE menu_items SET name_en = $$Mini Chocolate Coffee Croissant$$ WHERE name_he = $$מיני קרואסון שוקולד קפה$$;
UPDATE menu_items SET name_en = $$Mini Chocolate Coffee Croissant - Frozen$$ WHERE name_he = $$מיני קרואסון שוקולד קפה - קפוא$$;
UPDATE menu_items SET name_en = $$Mini Potato Pastry$$ WHERE name_he = $$מיני תפו"א$$;
UPDATE menu_items SET name_en = $$Diamond Bousha$$ WHERE name_he = $$מעויין בושה$$;
UPDATE menu_items SET name_en = $$Diamond Mushroom Pastry$$ WHERE name_he = $$מעויין פטריות$$;
UPDATE menu_items SET name_en = $$Diamond Almond Raspberry Pastry$$ WHERE name_he = $$מעויין שקדים פטל$$;
UPDATE menu_items SET name_en = $$Cheddar Parmesan Sticks$$ WHERE name_he = $$מקלות צדר פרמזן$$;
UPDATE menu_items SET name_en = $$Nemesis$$ WHERE name_he = $$נמסיס$$;
UPDATE menu_items SET name_en = $$Nemesis (Chalef)$$ WHERE name_he = $$נמסיס כשלפ$$;
UPDATE menu_items SET name_en = $$Citrus Sable$$ WHERE name_he = $$סבלה הדרים$$;
UPDATE menu_items SET name_en = $$Rose Sable Pack$$ WHERE name_he = $$סבלה ורדים מארז$$;
UPDATE menu_items SET name_en = $$Cocoa Sable$$ WHERE name_he = $$סבלה קקאו$$;
UPDATE menu_items SET name_en = $$Cocoa Sable Pack$$ WHERE name_he = $$סבלה קקאו מארז$$;
UPDATE menu_items SET name_en = $$Plain Donut$$ WHERE name_he = $$סופגניה ריקה$$;
UPDATE menu_items SET name_en = $$Cinnamon Bun$$ WHERE name_he = $$סינבון$$;
UPDATE menu_items SET name_en = $$Special Pain Suisse$$ WHERE name_he = $$ספיישל פאן סוויס$$;
UPDATE menu_items SET name_en = $$Special Strawberry & Cheese Patissiere$$ WHERE name_he = $$ספיישל תותים ופטיסייר גבינה$$;
UPDATE menu_items SET name_en = $$Cheesecake$$ WHERE name_he = $$עוגת גבינה$$;
UPDATE menu_items SET name_en = $$Pain Suisse - Cheese Patissiere & Choc Chips$$ WHERE name_he = $$פאן סוויס - פטיסייר גבינה ושוקוצ'יפס$$;
UPDATE menu_items SET name_en = $$Pain Suisse (Poppy Seed)$$ WHERE name_he = $$פאן סוויס (פרג)$$;
UPDATE menu_items SET name_en = $$Pain Suisse Nutella$$ WHERE name_he = $$פאן סוויס נוטלה$$;
UPDATE menu_items SET name_en = $$Focaccia 60/40$$ WHERE name_he = $$פוקצ׳ה 60/40$$;
UPDATE menu_items SET name_en = $$Focaccia Seeds/Sesame$$ WHERE name_he = $$פוקצ׳ה גרעינים/שומשום$$;
UPDATE menu_items SET name_en = $$Focaccia Sandwich 60/40$$ WHERE name_he = $$פוקצ׳ה כריכים 60/40$$;
UPDATE menu_items SET name_en = $$Florentine$$ WHERE name_he = $$פלורנטין$$;
UPDATE menu_items SET name_en = $$Florentine Pack$$ WHERE name_he = $$פלורנטין מארז$$;
UPDATE menu_items SET name_en = $$Palmier$$ WHERE name_he = $$פלמייה$$;
UPDATE menu_items SET name_en = $$Cheddar Parmesan Pack$$ WHERE name_he = $$צ׳דר פרמז׳ן מארז$$;
UPDATE menu_items SET name_en = $$Gianduja Cookie$$ WHERE name_he = $$קוקיז ג׳נדויה$$;
UPDATE menu_items SET name_en = $$Cocoa Cookie$$ WHERE name_he = $$קוקיז קקאו$$;
UPDATE menu_items SET name_en = $$Onion Quiche$$ WHERE name_he = $$קיש בצל$$;
UPDATE menu_items SET name_en = $$Kastan Brioche 1200$$ WHERE name_he = $$קסטן בריוש 1200$$;
UPDATE menu_items SET name_en = $$Kastan Brioche 600$$ WHERE name_he = $$קסטן בריוש 600$$;
UPDATE menu_items SET name_en = $$Kastan Brioche 700$$ WHERE name_he = $$קסטן בריוש 700$$;
UPDATE menu_items SET name_en = $$Kastan Country Bread$$ WHERE name_he = $$קסטן כפרי$$;
UPDATE menu_items SET name_en = $$Kastan Pecan Sourdough$$ WHERE name_he = $$קסטן מחמצת פקאן$$;
UPDATE menu_items SET name_en = $$Kastan 100% Whole Wheat$$ WHERE name_he = $$קסטן מלא 100%$$;
UPDATE menu_items SET name_en = $$Kastan Whole Wheat 70$$ WHERE name_he = $$קסטן מלא 70$$;
UPDATE menu_items SET name_en = $$Kastan Norwegian$$ WHERE name_he = $$קסטן נורווגי$$;
UPDATE menu_items SET name_en = $$Kastan Norwegian 1850$$ WHERE name_he = $$קסטן נורווגי 1850$$;
UPDATE menu_items SET name_en = $$Artichoke Cheese Pesto Croissant$$ WHERE name_he = $$קרואסון ארטישוק גבינה ופסטו$$;
UPDATE menu_items SET name_en = $$Danish Croissant$$ WHERE name_he = $$קרואסון דניש$$;
UPDATE menu_items SET name_en = $$Danish Croissant - Frozen$$ WHERE name_he = $$קרואסון דניש - קפוא$$;
UPDATE menu_items SET name_en = $$Butter Croissant$$ WHERE name_he = $$קרואסון חמאה$$;
UPDATE menu_items SET name_en = $$Butter Croissant - Frozen$$ WHERE name_he = $$קרואסון חמאה - קפוא$$;
UPDATE menu_items SET name_en = $$Lemon Croissant$$ WHERE name_he = $$קרואסון לימון$$;
UPDATE menu_items SET name_en = $$Mini Butter Croissant - Frozen$$ WHERE name_he = $$קרואסון מיני חמאה -קפוא$$;
UPDATE menu_items SET name_en = $$Mini Butter Croissant - Frozen$$ WHERE name_he = $$קרואסון מיני חמאה- קפוא$$;
UPDATE menu_items SET name_en = $$Pistachio Croissant$$ WHERE name_he = $$קרואסון פיסטוק$$;
UPDATE menu_items SET name_en = $$Double Pistachio Croissant (Special)$$ WHERE name_he = $$קרואסון פיסטוק זוגי (ספיישל)$$;
UPDATE menu_items SET name_en = $$Pecan Caramel Croissant$$ WHERE name_he = $$קרואסון פקאן קרמל$$;
UPDATE menu_items SET name_en = $$Provence Croissant$$ WHERE name_he = $$קרואסון פרובנס$$;
UPDATE menu_items SET name_en = $$Ricotta Croissant$$ WHERE name_he = $$קרואסון ריקוטה$$;
UPDATE menu_items SET name_en = $$Chocolate Croissant$$ WHERE name_he = $$קרואסון שוקולד$$;
UPDATE menu_items SET name_en = $$Chocolate Croissant - Frozen$$ WHERE name_he = $$קרואסון שוקולד - קפוא$$;
UPDATE menu_items SET name_en = $$Almond Croissant$$ WHERE name_he = $$קרואסון שקדים$$;
UPDATE menu_items SET name_en = $$Almond & Pear Croissant$$ WHERE name_he = $$קרואסון שקדים ואגסים$$;
UPDATE menu_items SET name_en = $$Salted Caramel$$ WHERE name_he = $$קרמל מלוח$$;
UPDATE menu_items SET name_en = $$Walnut Kranz$$ WHERE name_he = $$קרנץ אגוזים$$;
UPDATE menu_items SET name_en = $$Halva Kranz$$ WHERE name_he = $$קרנץ חלבה$$;
UPDATE menu_items SET name_en = $$Halva Kranz$$ WHERE name_he = $$קרנץ חלווה$$;
UPDATE menu_items SET name_en = $$Chocolate Kranz$$ WHERE name_he = $$קרנץ שוקולד$$;
UPDATE menu_items SET name_en = $$Gluten-Free Crackers Pack$$ WHERE name_he = $$קרקרים ללא גלוטן מארז$$;
UPDATE menu_items SET name_en = $$Crackers Pack$$ WHERE name_he = $$קרקרים מארז$$;
UPDATE menu_items SET name_en = $$Rugelach$$ WHERE name_he = $$רוגעלך$$;
UPDATE menu_items SET name_en = $$Rugelach - Frozen$$ WHERE name_he = $$רוגעלך - קפוא$$;
UPDATE menu_items SET name_en = $$Date & Walnut Roulade Pack$$ WHERE name_he = $$רולדה תמרים ואגוזים מארז$$;
UPDATE menu_items SET name_en = $$Jam$$ WHERE name_he = $$ריבה$$;
UPDATE menu_items SET name_en = $$Chocolate Squares Pack$$ WHERE name_he = $$ריבועי שוקולד מארז$$;
UPDATE menu_items SET name_en = $$Squares - Frozen$$ WHERE name_he = $$ריבועים- קפוא$$;
UPDATE menu_items SET name_en = $$Plain$$ WHERE name_he = $$ריקה$$;
UPDATE menu_items SET name_en = $$Chausson$$ WHERE name_he = $$שוסון$$;
UPDATE menu_items SET name_en = $$Chocolate$$ WHERE name_he = $$שוקולד$$;
UPDATE menu_items SET name_en = $$Apple Strudel$$ WHERE name_he = $$שטרודל תפוחים$$;
UPDATE menu_items SET name_en = $$100% Rye$$ WHERE name_he = $$שיפון 100%$$;
UPDATE menu_items SET name_en = $$Poppy Seed Layers$$ WHERE name_he = $$שכבות פרג$$;
UPDATE menu_items SET name_en = $$Individual Halva Yeast Cake$$ WHERE name_he = $$שמרים חלבה אישי$$;
UPDATE menu_items SET name_en = $$Large Halva Yeast Cake$$ WHERE name_he = $$שמרים חלבה גדולה$$;
UPDATE menu_items SET name_en = $$Individual Chocolate Yeast Cake$$ WHERE name_he = $$שמרים שוקולד אישי$$;
UPDATE menu_items SET name_en = $$Large Chocolate Yeast Cake$$ WHERE name_he = $$שמרים שוקולד גדולה$$;
UPDATE menu_items SET name_en = $$Almond & Pear$$ WHERE name_he = $$שקדים ואגסים$$;
